global using CommonBasicLibraries.CollectionClasses;
global using System.Xml.Linq;
global using UpdateManager.CoreLibrary.Interfaces;
global using UpdateManager.CoreLibrary.NugetHelpers;
global using UpdateManager.CoreLibrary.Models;
global using Microsoft.Extensions.Configuration;
global using UpdateManager.CoreLibrary.Utilities;
global using System.Diagnostics;
global using bb1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using jj1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.FileHelpers;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using System.Text;
global using UpdateManager.DotNetUpgradeLibrary.Models;
global using UpdateManager.CoreLibrary.TemplateHelpers;
global using UpdateManager.DotNetUpgradeLibrary.Interfaces;
global using UpdateManager.DotNetUpgradeLibrary.Extensions;
global using UpdateManager.DotNetUpgradeLibrary.TestHelpers;
global using UpdateManager.DotNetUpgradeLibrary.Utilities;
global using UpdateManager.CoreLibrary.ProjectFileHelpers;
global using Microsoft.Extensions.DependencyInjection;
global using UpdateManager.DotNetUpgradeLibrary.Services;
global using UpdateManager.CoreLibrary.DataAccess;
